version: "3.8"

services:
 server:
  build: .
  container_name: server
  depends_on:
   - database
  env_file: .env
  networks:
   - ft_transcendence
  ports:
   - "3000:3000"
  restart: always

 database:
  container_name: database
  env_file: .env
  image: postgres:latest
  networks:
   - ft_transcendence
  restart: always

 database_gui:
  container_name: database_gui
  depends_on:
   - database
  image: adminer
  networks:
   - ft_transcendence
  ports:
   - 8080:8080
  restart: always

networks:
  ft_transcendence:
