const PADDLEHEIGHT = 100;
const WINDOWWIDTH = 600;
const WINDOWHEIGHT = 400;
const MIDDLE_WIN = 150;
const DFSPEED = 3;
const DFRADIUS = 10;

export {
  PADDLEHEIGHT,
  WINDOWWIDTH,
  WINDOWHEIGHT,
  MIDDLE_WIN,
  DFSPEED,
  DFRADIUS,
};
